const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const NotificationSchema = new Schema({
    // text is generated by the server
    text: {
        type: String,
        required: true
    },
    // message is optional from the client
    message: {
        type: String,
        required: false
    },
    read: {
        type: Boolean,
        default: false
    },
    actions: [{
        type: Schema.Types.ObjectId,
        ref: 'NotificationAction',
        required: false
    }],
    // if the user is registered, we need to store their id (for notification)
    user: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: false
    },
    
    // if the user is not registered, we need to store their email (for invitation to join group)
    email: {
        type: String,
        required: false
    },
    // type of notification (personal, group, invitation)
    type:{
        type: String,
        required: true
    },
    group: {
        type: Schema.Types.ObjectId,
        ref: 'Group',
        required: false
    },
    // actor is the person who triggered the notification
    actor: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        required: false
    },


}, {timestamps: true});

const Notification = mongoose.model('Notification', NotificationSchema);
module.exports = Notification;

    